---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[awesome_customers::default]
    provisioner:
      # On a Windows workstation, set to C:\temp\encrypted_data_bag_secret.
      encrypted_data_bag_secret_key_path: /tmp/encrypted_data_bag_secret
    attributes:
      awesome_customers:
        passwords:
          secret_path: '/tmp/kitchen/encrypted_data_bag_secret'